version: '3.8'
services:
  db:
    profiles:
      - dev
      - debug
    image: postgres:17
    container_name: meatway-db
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 3s
      timeout: 5s
    volumes:
      - ./src/main/resources/schema_init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - internal

  meatway-api:
    profiles:
      - dev
    build:
      context: .
      dockerfile: Dockerfile

    container_name: meatway-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_URL: ${DB_URL}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - internal

networks:
  internal:
    name: internal
    driver: bridge