spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5433/meatway_db_container?currentSchema=business
    username: postgres
    password: postgres