spring:
  application:
    name: app

  liquibase:
    default-schema: business
    change-log: classpath:liquibase/master.xml

logging:
  level:
    org.flywaydb: DEBUG

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem