spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:mem://localhost:5433/meatway
    username: h2
    password: password
  flyway:
    enabled: false
    locations: classpath:db/migration